name: "Copy dlls for windows"
description: "Copy dlls for windows"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        vcruntime=$(find /c/Program\ Files/Microsoft\ Visual\ Studio -name vcruntime140_1.dll -print -quit)
        test -n "$vcruntime"
        cp "$vcruntime" packages/vaex-core/vaex/
        mkdir packages/vaex-core/vendor/pcre
        cd packages/vaex-core/vendor/pcre
        curl https://anaconda.org/conda-forge/pcre/8.44/download/win-64/pcre-8.44-h6538335_0.tar.bz2 -Lo pcre.tar.bz2
        tar jxfv pcre.tar.bz2
        cd ../../
        cp vendor/pcre/Library/bin/*.dll vaex/
        cd ../../
